#!/bin/sh
set -eu
/usr/sbin/chown -R root:wheel '/Library/PrivilegedHelperTools/foxVPN'
/bin/chmod 755 '/Library/PrivilegedHelperTools/foxVPN' '/Library/PrivilegedHelperTools/foxVPN/component'
/bin/chmod 644 '/Library/PrivilegedHelperTools/foxVPN/component/binding.json' '/Library/PrivilegedHelperTools/foxVPN/floor.json' '/Library/PrivilegedHelperTools/foxVPN/component/network-version.json'
/usr/sbin/chown root:wheel /Library/PrivilegedHelperTools/foxVPN/component/helper /Library/LaunchDaemons/ru.smartvpn.router.network.plist
/bin/chmod 755 '/Library/PrivilegedHelperTools/foxVPN/component/helper' '/Library/PrivilegedHelperTools/foxVPN/component/core'
/bin/chmod 644 /Library/LaunchDaemons/ru.smartvpn.router.network.plist
/usr/bin/touch /Library/Logs/foxVPN-network.log
/usr/sbin/chown root:wheel /Library/Logs/foxVPN-network.log
/bin/chmod 600 /Library/Logs/foxVPN-network.log
/bin/launchctl bootout system/ru.smartvpn.router.network 2>/dev/null || true
/bin/rm -f /Library/PrivilegedHelperTools/ru.smartvpn.router.network /Library/PrivilegedHelperTools/foxVPN/client.cdhash /Library/PrivilegedHelperTools/foxVPN/client.uid /Library/PrivilegedHelperTools/foxVPN/core /Library/PrivilegedHelperTools/foxVPN/network-version.json
/bin/launchctl bootstrap system /Library/LaunchDaemons/ru.smartvpn.router.network.plist
exit 0
