import React,{useEffect,useRef,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {startVisiblePolling} from './polling';
type Status={supported:boolean;enabled:boolean;matches:boolean;script_configured:boolean;script_active?:boolean;auto_detect?:boolean};
export function WindowsProxySetup({connected,port,automatic=false}:{connected:boolean;port:number;automatic?:boolean}){
 const [status,setStatus]=useState<Status|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const generation=useRef(0);
 async function check(){const id=++generation.current;try{const next=await invoke<Status>('windows_proxy_status');if(id!==generation.current)return;setStatus(next);setError('')}catch(e){if(id!==generation.current)return;setError(String(e));setStatus(null)}}
 useEffect(()=>{void check();const stop=startVisiblePolling(async()=>{await check()},5000);return()=>{generation.current+=1;stop()}},[port,connected]);
 async function open(){setBusy(true);try{await invoke('open_windows_proxy_settings');setError('')}catch(e){setError(String(e))}finally{setBusy(false)}}
 const ambiguous=!!(status?.script_active||status?.auto_detect);
 const matched=!!status?.matches&&!ambiguous;
 return <section className="panel setting-panel" aria-label="Подключение браузера Windows"><div className="panel-heading"><h3>Прокси для браузеров Windows</h3><span className={`badge ${matched&&connected?'success':'warning'}`}>{!status?'Настройка не проверена':ambiguous?'Включены автоматические параметры Windows':matched?connected?'Прокси Windows настроен':'Прокси Windows включён, foxVPN отключён':'Прокси Windows не указывает на foxVPN'}</span></div><p>{matched?connected?'Параметры Windows указывают на foxVPN. Совместимые программы могут использовать это подключение.':'Сейчас адрес foxVPN остаётся в настройках Windows, но локальный прокси отключён. Подключите foxVPN или выключите ручной прокси Windows.':automatic?'Автоматическая настройка разрешена: после успешного подключения foxVPN включит прокси Windows. При отключении восстановит прежние параметры.':'Локальный прокси сам по себе не меняет подключение Chrome и Edge. Откройте параметры Windows и укажите ручной HTTP-прокси.'}</p><p><b>Адрес: 127.0.0.1 · порт: {port}</b></p>{ambiguous&&<p className="footnote">Включён сценарий или автоматическое определение прокси. Они могут изменить маршрут браузера. Нажмите «Проверить и настроить», чтобы подтвердить автоматическую настройку foxVPN.</p>}{status?.script_configured&&!ambiguous&&<p className="footnote">Сохранён адрес сценария автоматической настройки. Если сценарий включён, он может задавать другой маршрут браузера; перед изменением сохраните прежние параметры.</p>}<div className="bottom-toolbar"><button className="primary" disabled={busy} onClick={()=>void open()}>Открыть прокси Windows</button><button className="secondary" disabled={busy} onClick={()=>void check()}>Проверить настройку браузера</button></div><p className="footnote">{automatic?'foxVPN автоматически настраивает ручной прокси после проверки подключения и восстанавливает прежние параметры при отключении или выходе. Отдельный процесс восстанавливает их при аварийном закрытии. Если прокси изменён вами или другой программой, это изменение сохраняется. При следующем запуске проверяется незавершённое восстановление.':'foxVPN только проверяет и открывает параметры — изменение вы подтверждаете в Windows. Перед изменением сохраните прежние значения. После отключения foxVPN выключите ручной прокси или верните прежние настройки.'} Это не VPN для всех программ и не защита при обрыве. Расширения браузера и собственные настройки программ могут задавать другой маршрут.</p><p className="footnote">В «Умном» режиме домены .ru, .su и .рф идут напрямую. Сайт определения IP в этих зонах покажет обычный IP — это выбранное правило маршрутизации.</p>{error&&<p role="status">{error}</p>}</section>;
}
